"""Closed enums and immutable constants for Big Trades V2."""

from __future__ import annotations

from enum import Enum


LOGIC_VERSION = "BTLOGIC-2.0"
INPUT_MODE_AGGREGATE_TRADES = "AGGREGATE_TRADES"
SESSION_TEMPLATE = "CRYPTO_UTC_DAY"
QUANTITY_UNIT = "BASE_ASSET"
AGGREGATION_WINDOW_MS = 40
AGGREGATION_CANDLE_TIMEFRAME = "1m"
DEFAULT_HORIZONS_SECONDS = (1, 5, 15, 30, 60, 180, 300, 600)
ASSESSMENT_NOTE_MAX_LENGTH = 2000


class FilterMode(str, Enum):
    MANUAL = "MANUAL"
    AUTOMATIC = "AUTOMATIC"


class AutomaticIntensity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    STRONG = "STRONG"


class SideFilter(str, Enum):
    BOTH = "BOTH"
    BUY = "BUY"
    SELL = "SELL"


class MarkerPriceMode(str, Enum):
    START_PRICE = "START_PRICE"
    LAST_PRICE = "LAST_PRICE"
    VWAP_PRICE = "VWAP_PRICE"


class ClusterCloseReason(str, Enum):
    SIDE_CHANGED = "SIDE_CHANGED"
    TIME_GAP_EXCEEDED = "TIME_GAP_EXCEEDED"
    SESSION_CHANGED = "SESSION_CHANGED"
    CANDLE_CHANGED = "CANDLE_CHANGED"
    STREAM_ENDED = "STREAM_ENDED"
    STREAM_DISCONNECTED = "STREAM_DISCONNECTED"
    SYMBOL_CHANGED = "SYMBOL_CHANGED"
    SETTINGS_FORCED_FLUSH = "SETTINGS_FORCED_FLUSH"
    MAX_FILLS_EXCEEDED = "MAX_FILLS_EXCEEDED"


class FilterDecisionReason(str, Enum):
    ACCEPT = "ACCEPT"
    REJECT_BELOW_MIN = "REJECT_BELOW_MIN"
    REJECT_ABOVE_MAX = "REJECT_ABOVE_MAX"
    AUTOMATIC_UNAVAILABLE = "AUTOMATIC_UNAVAILABLE"


class PriceRelation(str, Enum):
    ABOVE = "ABOVE"
    INSIDE = "INSIDE"
    BELOW = "BELOW"


class InteractionType(str, Enum):
    ZONE_CREATED = "ZONE_CREATED"
    FIRST_EXIT_UP = "FIRST_EXIT_UP"
    FIRST_EXIT_DOWN = "FIRST_EXIT_DOWN"
    TOUCH_FROM_ABOVE = "TOUCH_FROM_ABOVE"
    TOUCH_FROM_BELOW = "TOUCH_FROM_BELOW"
    REENTER_FROM_ABOVE = "REENTER_FROM_ABOVE"
    REENTER_FROM_BELOW = "REENTER_FROM_BELOW"
    CROSS_UP = "CROSS_UP"
    CROSS_DOWN = "CROSS_DOWN"
    RELATION_ABOVE = "RELATION_ABOVE"
    RELATION_INSIDE = "RELATION_INSIDE"
    RELATION_BELOW = "RELATION_BELOW"
    SOURCE_GAP_STARTED = "SOURCE_GAP_STARTED"
    SOURCE_GAP_ENDED = "SOURCE_GAP_ENDED"
    ZONE_SESSION_CLOSED = "ZONE_SESSION_CLOSED"


class ZoneLifecycle(str, Enum):
    ACTIVE = "ACTIVE"
    ACTIVE_WITH_GAP = "ACTIVE_WITH_GAP"
    SESSION_CLOSED = "SESSION_CLOSED"
    ERROR = "ERROR"


class SnapshotValidity(str, Enum):
    VALID = "VALID"
    MISSING_NO_TRADE = "MISSING_NO_TRADE"
    MISSING_STALE = "MISSING_STALE"
    MISSING_SOURCE_GAP = "MISSING_SOURCE_GAP"
    MISSING_SESSION = "MISSING_SESSION"


class CandleResultLabel(str, Enum):
    CLOSE_ABOVE = "CLOSE_ABOVE"
    CLOSE_BELOW = "CLOSE_BELOW"
    UPPER_WICK_RETURN = "UPPER_WICK_RETURN"
    LOWER_WICK_RETURN = "LOWER_WICK_RETURN"
    CLOSED_INSIDE = "CLOSED_INSIDE"


class UserAssessmentValue(str, Enum):
    UNASSESSED = "UNASSESSED"
    EFFORT_REWARDED = "EFFORT_REWARDED"
    EFFORT_NOT_REWARDED = "EFFORT_NOT_REWARDED"
    OPPOSING_ABSORPTION_OBSERVED = "OPPOSING_ABSORPTION_OBSERVED"
    REPEATED_DEFENSE_OBSERVED = "REPEATED_DEFENSE_OBSERVED"
    BREAK_ACCEPTED_OBSERVED = "BREAK_ACCEPTED_OBSERVED"
    BATTLE_UNRESOLVED = "BATTLE_UNRESOLVED"
    CONTROL_UP_OBSERVED = "CONTROL_UP_OBSERVED"
    CONTROL_DOWN_OBSERVED = "CONTROL_DOWN_OBSERVED"


class CalibrationStatus(str, Enum):
    VALID = "VALID"
    INSUFFICIENT_HISTORY = "INSUFFICIENT_HISTORY"
